version: "3.8"

services:
  keepalived_operator:
    image: ghcr.io/isqiao/keepalived-swarm:0e7b1ea9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - host
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      KEEPALIVED_GROUP: "production"
      KEEPALIVED_VIRTUAL_IPS: "192.168.31.201,192.168.1.202"
      KEEPALIVED_INTERFACE: "ens18"
      KEEPALIVED_PASSWORD: "8cteD88Hq4SZpPxm"
      KEEPALIVED_ROUTER_ID: "51"

networks:
  host:
    external: true
    name: host
